# SPDX-FileCopyrightText: 2019 Kattni Rembor for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: AdaBot

on:
  workflow_run:
    workflows: ["Build CI"]
    types:
      - completed

jobs:
  adabot-help:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Post comment to help
      uses: adafruit/circuitpython-action-library-ci-failed@v0
